<Project Sdk="Godot.NET.Sdk/4.6.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CommonSDK</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Event\README.md" />
      <Content Include="Logger\README.md" />
      <Content Include="Utils\README-F.md" />
    </ItemGroup>

</Project>
